name: hw1_env
dependencies:
	- python=3.8
	- pip
	- pip:
		- numpy==1.202
		- pandas==1.2.4
		- scipy
		- matplotlib
		- pandas
		- scikit-learn
		- missingno
		- feature_engine
		- pylab-sdk
		- seaborn
		- xgboost
		- researchpy